'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { cn } from '@/lib/utils';
import { useMe } from '@/hooks/use-auth';
import { LayoutDashboard,Calendar,BookOpen,CalendarDays,Bell,User as UI,Shield,Users,Layers,GraduationCap,UserPlus,ChevronDown,Menu,X } from 'lucide-react';
import { useState } from 'react';
const MN=[{href:'/dashboard',label:'Dashboard',icon:LayoutDashboard},{href:'/schedule',label:'Schedule',icon:Calendar},{href:'/courses',label:'Courses',icon:BookOpen},{href:'/calendar',label:'Calendar',icon:CalendarDays},{href:'/notifications',label:'Notifications',icon:Bell},{href:'/profile',label:'Profile',icon:UI}];
const AN=[{href:'/admin',label:'Overview',icon:Shield},{href:'/admin/users',label:'Users',icon:Users},{href:'/admin/groups',label:'Groups',icon:Layers},{href:'/admin/courses',label:'Courses',icon:BookOpen},{href:'/admin/enrollments',label:'Enrollments',icon:UserPlus}];
export function Sidebar(){const path=usePathname();const{data:user}=useMe();const[ao,sao]=useState(path.startsWith('/admin'));const[mo,smo]=useState(false);
const ia=(h:string)=>path===h||(h!=='/dashboard'&&h!=='/admin'&&path.startsWith(h+'/'));
const lk=(i:typeof MN[0])=>(<Link key={i.href} href={i.href} onClick={()=>smo(false)} className={cn('flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors',ia(i.href)?'bg-primary text-primary-foreground':'text-muted-foreground hover:bg-accent hover:text-accent-foreground')}><i.icon className="h-4 w-4"/>{i.label}</Link>);
const inner=(<><div className="p-4 border-b"><Link href="/dashboard" className="flex items-center gap-2"><GraduationCap className="h-7 w-7 text-primary"/><span className="font-bold text-lg">UniLMS</span></Link></div><nav className="flex-1 p-3 space-y-1 overflow-y-auto">{MN.map(lk)}{user?.role==='ADMIN'&&(<><button onClick={()=>sao(!ao)} className="flex w-full items-center gap-2 px-3 py-2 mt-4 text-xs font-semibold uppercase tracking-wider text-muted-foreground hover:text-foreground">Administration<ChevronDown className={cn('h-3 w-3 ml-auto transition-transform',ao&&'rotate-180')}/></button>{ao&&AN.map(lk)}</>)}</nav><div className="border-t p-3"><div className="flex items-center gap-3 px-3 py-2"><div className="h-8 w-8 rounded-full bg-primary/10 flex items-center justify-center text-sm font-semibold text-primary">{user?.fullName?.charAt(0)??'?'}</div><div className="flex-1 min-w-0"><p className="text-sm font-medium truncate">{user?.fullName}</p><p className="text-xs text-muted-foreground">{user?.role}</p></div></div></div></>);
return(<><button onClick={()=>smo(true)} className="fixed top-4 left-4 z-40 lg:hidden rounded-md border bg-background p-2 shadow"><Menu className="h-5 w-5"/></button>{mo&&(<div className="fixed inset-0 z-40 lg:hidden"><div className="fixed inset-0 bg-black/50" onClick={()=>smo(false)}/><div className="fixed left-0 top-0 bottom-0 w-64 bg-background border-r flex flex-col z-50"><button onClick={()=>smo(false)} className="absolute top-4 right-4"><X className="h-5 w-5"/></button>{inner}</div></div>)}<aside className="hidden lg:flex lg:flex-col lg:w-64 lg:border-r lg:bg-background lg:fixed lg:inset-y-0">{inner}</aside></>);}
