'use client';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api';
import type { CalendarData } from '@/lib/types';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/form-elements';
import { ChevronLeft, ChevronRight } from 'lucide-react';
const MN=['January','February','March','April','May','June','July','August','September','October','November','December'];const WD=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
export default function CalendarPage(){const now=new Date();const[y,sY]=useState(now.getFullYear());const[m,sM]=useState(now.getMonth()+1);const ms=`${y}-${String(m).padStart(2,'0')}`;const{data,isLoading}=useQuery<CalendarData>({queryKey:['cal',ms],queryFn:()=>api.get(`/me/calendar?month=${ms}`)});const prev=()=>{if(m===1){sM(12);sY(y-1);}else sM(m-1);};const next=()=>{if(m===12){sM(1);sY(y+1);}else sM(m+1);};const fd=new Date(y,m-1,1);const ld=new Date(y,m,0);const sw=fd.getDay()===0?6:fd.getDay()-1;const cells:(number|null)[]=[];for(let i=0;i<sw;i++)cells.push(null);for(let d=1;d<=ld.getDate();d++)cells.push(d);while(cells.length%7!==0)cells.push(null);const evts=(day:number)=>{const ds=`${y}-${String(m).padStart(2,'0')}-${String(day).padStart(2,'0')}`;return{si:(data?.scheduleItems||[]).filter(s=>s.startsAt.slice(0,10)===ds),as:(data?.assignments||[]).filter(a=>a.dueAt.slice(0,10)===ds)};};const isT=(d:number)=>d===now.getDate()&&m===now.getMonth()+1&&y===now.getFullYear();return(<div className="space-y-4"><div className="flex items-center justify-between"><h1 className="text-2xl font-bold">Calendar</h1><div className="flex items-center gap-2"><Button variant="outline" size="icon" onClick={prev}><ChevronLeft className="h-4 w-4"/></Button><span className="text-sm font-medium min-w-[140px] text-center">{MN[m-1]} {y}</span><Button variant="outline" size="icon" onClick={next}><ChevronRight className="h-4 w-4"/></Button></div></div><Card><CardContent className="p-0">{isLoading?<div className="p-6"><Skeleton className="h-[500px] w-full"/></div>:<div><div className="grid grid-cols-7 border-b">{WD.map(d=><div key={d} className="p-3 text-center text-xs font-semibold text-muted-foreground">{d}</div>)}</div><div className="grid grid-cols-7">{cells.map((day,i)=>{const e=day?evts(day):{si:[],as:[]};return(<div key={i} className={`min-h-[100px] p-2 border-b border-r ${!day?'bg-muted/30':''} ${day&&isT(day)?'bg-primary/5':''}`}>{day&&<><span className={`text-sm ${isT(day)?'bg-primary text-white rounded-full w-7 h-7 flex items-center justify-center font-bold':'text-muted-foreground'}`}>{day}</span><div className="mt-1 space-y-0.5">{e.si.slice(0,2).map(s=><div key={s.id} className="text-[10px] px-1 py-0.5 rounded bg-blue-100 text-blue-700 truncate">{s.course?.code}</div>)}{e.as.slice(0,2).map(a=><div key={a.id} className="text-[10px] px-1 py-0.5 rounded bg-red-100 text-red-700 truncate">Due: {a.title}</div>)}</div></>}</div>);})}</div></div>}</CardContent></Card></div>);}
