'use client';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api';
import type { Notification } from '@/lib/types';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/form-elements';
import { cn, formatDateTime } from '@/lib/utils';
import { Bell, Check, CheckCheck, Award, MessageSquare, Clock } from 'lucide-react';
import Link from 'next/link';
const IC:Record<string,any>={ANNOUNCEMENT:MessageSquare,GRADE_PUBLISHED:Award,ASSIGNMENT_DUE:Clock,SYSTEM:Bell};
export default function NotificationsPage(){const qc=useQueryClient();const{data:notifs,isLoading}=useQuery<Notification[]>({queryKey:['notifs'],queryFn:()=>api.get('/me/notifications')});const mr=useMutation({mutationFn:(id:string)=>api.post(`/me/notifications/${id}/read`),onSuccess:()=>{qc.invalidateQueries({queryKey:['notifs']});qc.invalidateQueries({queryKey:['nc']});}});const ma=useMutation({mutationFn:()=>api.post('/me/notifications/read-all'),onSuccess:()=>{qc.invalidateQueries({queryKey:['notifs']});qc.invalidateQueries({queryKey:['nc']});}});const uc=(notifs||[]).filter(n=>!n.isRead).length;return(<div className="space-y-4"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Notifications</h1><p className="text-muted-foreground">{uc} unread</p></div>{uc>0&&<Button variant="outline" size="sm" onClick={()=>ma.mutate()} className="gap-2"><CheckCheck className="h-4 w-4"/>Mark all read</Button>}</div>{isLoading?<div className="space-y-3">{[1,2,3].map(i=><Skeleton key={i} className="h-16 w-full"/>)}</div>:!notifs?.length?<Card><CardContent className="py-12 text-center text-muted-foreground"><Bell className="h-8 w-8 mx-auto mb-2 opacity-30"/>No notifications</CardContent></Card>:<div className="space-y-2">{notifs.map(n=>{const I=IC[n.type]||Bell;return(<Card key={n.id} className={cn(!n.isRead&&'border-primary/30 bg-primary/[0.02]')}><CardContent className="py-3 flex items-start gap-3"><div className={cn('mt-0.5 h-8 w-8 rounded-full flex items-center justify-center flex-shrink-0',!n.isRead?'bg-primary/10':'bg-muted')}><I className={cn('h-4 w-4',!n.isRead?'text-primary':'text-muted-foreground')}/></div><div className="flex-1 min-w-0"><div className="flex items-start justify-between gap-2">{n.link?<Link href={n.link} className="hover:underline"><p className={cn('text-sm',!n.isRead&&'font-semibold')}>{n.title}</p></Link>:<p className={cn('text-sm',!n.isRead&&'font-semibold')}>{n.title}</p>}{!n.isRead&&<Button size="sm" variant="ghost" onClick={()=>mr.mutate(n.id)} className="h-7"><Check className="h-3 w-3"/></Button>}</div>{n.body&&<p className="text-xs text-muted-foreground mt-0.5">{n.body}</p>}<p className="text-[10px] text-muted-foreground mt-1">{formatDateTime(n.createdAt)}</p></div></CardContent></Card>);})}</div>}</div>);}
